### ISSUE TITLE
[$1000,$800] Drone Series - Move Mission Planner to React APP

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/dsp-frontend#1]
For this challenge we want to move our Mission Planner component from the [dsp-app demo](https://github.com/topcoderinc/dsp-app/tree/master/src/components/mission)  and integrated it [here in our React  dsp-frontend ](https://github.com/topcoderinc/dsp-frontend).   Don't worry about navigation to the  Mission Planner you can just create a static route put please follow the conventions of the other components. 

The purpose of the mission planner is to allow pilots to plan autopilot missions to be executed on their drones.   The demo code which is found in the [dsp-app Repo](https://github.com/topcoderinc/dsp-app) is based on facebook's reacte-create-app generator but now in its [new home ](https://github.com/topcoderinc/dsp-frontend) it will be organized a little better.

We would love for you to attempt to wire the mission planner to [ our dsp API mission endpoint](https://github.com/topcoderinc/dsp-server) and you can see this live [swagger doc at ](http://kb-dsp-server.herokuapp.com/api-docs/) however it appears that we have removed the /mission POST endpoint and the time of writing this so you may just write the payload to the console.  We hope to have the mission POST endpoint back up very soon.

![screen shot 2016-12-06 at 4 22 03 pm](https://cloud.githubusercontent.com/assets/1180747/20946412/30f05600-bbd0-11e6-8aed-1825fa3b949f.png)

**Comment by kbowerma** [comment]
Failed to create challenge
Status code: 503
Response body:
```
"<!DOCTYPE html>\n\t<html>\n\t  <head>\n\t\t<meta charset=\"utf-8\">\n\t\t<title>Application Error</title>\n\t\t<style media=\"screen\">\n\t\t  html,body,iframe {\n\t\t\tmargin: 0;\n\t\t\tpadding: 0;\n\t\t  }\n\t\t  html,body {\n\t\t\theight: 100%;\n\t\t\toverflow: hidden;\n\t\t  }\n\t\t  iframe {\n\t\t\twidth: 100%;\n\t\t\theight: 100%;\n\t\t\tborder: 0;\n\t\t  }\n\t\t</style>\n\t  </head>\n\t  <body>\n\t\t<iframe src=\"//www.herokucdn.com/error-pages/application-error.html\"></iframe>\n\t  </body>\n\t</html>"
```

**Comment by kbowerma** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/30055900/?type=develop&noncache=true

**Comment by cwdcwd** [comment]
@kbowerma how often are you seeing the TC API timeout as above? Do you have a rough estimate on the wait time there? I'm seeing upwards of 30s in the logs
