### ISSUE TITLE
On Heroku, ENV vars aren't honored.

### ISSUE THREAD

**Issue by mtwomey** [topcoderinc/dsp-frontend#12]
We're on Heroku now - awesome! Frontend config variables can't be overridden by Heroku env settings right now though. They are falling through to their backup values:

`API_BASE_PATH: process.env.API_BASE_PATH || 'https://kb-dsp-server-dev.herokuapp.com'`

This falls through to `'https://kb-dsp-server-dev.herokuapp.com'` regardless of what you have set `API_BASE_PATH` to in Heroku. Maybe this has to do with webpack?

**Comment by mtwomey** [comment]
Or maybe it's looking at my browser side env?

**Comment by gondzo** [comment]
The variables need to be set before the build. Only those defined in webpack.config.js#100 (DefinePlugin) will be filled out. Also, we have 2 config files one in config/*.js and this one is read by the server app hosting process, and the second one is in src/config.index.js
I'll push a fix for this later.
