### ISSUE TITLE
[$80] When you log in (successfully) the login window remains open (also when you log out)

### ISSUE THREAD

**Issue by mtwomey** [topcoderinc/dsp-frontend#19]
When you logout also there is no refresh of the screen (showing that you're logged out).
![screen shot 2017-01-03 at 5 14 45 pm](https://cloud.githubusercontent.com/assets/7715262/21626690/3db94b76-d1d8-11e6-9c3f-7a6a5e3f2c25.png)

**Comment by maxceem** [comment]
It looks like there are also some other side effects of this bug with login which I ran into when participating challenge https://www.topcoder.com/challenge-details/30056080/?type=develop

Let's say I login as a pilot and redirect user to the pilot mission list page.
Even though login window could close successfully, but when performing request to the server if I need information about logged in user it could be not there yet:
- `accessToken` could be still undefined in `APIService`
- `state.global.user.id` could be still undefined too

**Comment by maxceem** [comment]
You can set poor network conditions in the Chrome dev tools, I think you will 100% get it.
http://joxi.ru/812Myw4TEDkq2J

**Comment by mtwomey** [comment]
Also note that there are supposed to be additional menu entries after you log in. I've been refreshing my browser after I enter my credential to get that login window to disappear. This allows the new menu items to show up. However, I just realized that I can also click the 'X' on the login window. However when I do that, the box closes - but the new menu items don't appear. The intention here is to fix it so that it works correctly (including the menu) when the user logs in / logs out.

![screen shot 2017-01-04 at 10 20 33 am](https://cloud.githubusercontent.com/assets/7715262/21649666/1d03922a-d268-11e6-9369-eeaa6d399fe4.png)

**Comment by birdofpreyru** [comment]
Ready. You may consider to up the payment a bit, as it was not just that smb forgot to close the modal after login, but the login logic as whole had flaws and was not implemented in the correct React/Redux way. So I had to dig into it a bit, to find out what is going on, and how it should be re-written.

**Comment by gondzo** [comment]
Form login works correctly, but still need to refresh the page on social login. AuthService#parseHash doesn't even try do anything but set the key on login. Can you clear that up too ?
Payment increased to 80$

**Comment by birdofpreyru** [comment]
Done #27

**Comment by birdofpreyru** [comment]
@mtwomey @gondzo Any plans to pay for this and #18 any soon? Both payments are pending for one month.

Also, I'm wondering what's up with this project? It was very active around the New Year, many challenges and staff going on, but I have not seen that much activity recently.

**Comment by gondzo** [comment]
It will be handled today

**Comment by kbowerma** [comment]
Payment Scheduled:   https://apps.topcoder.com/bugs/browse/DRONESERIES-7

**Comment by birdofpreyru** [comment]
@kbowerma Two days later, the payment is still not in my PACTS, can you verify everything is correct (I don't have permissions to access the URL in your last comment myself)? Same with the other one (https://github.com/topcoderinc/dsp-frontend/issues/18)

**Comment by kbowerma** [comment]
Sorry My fault you should see it soon
