### ISSUE TITLE
Move MyDrones from jakarta to the southwest

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/dsp-frontend#21]
Also try to decrease the icon size:

![screen shot 2017-01-04 at 1 34 15 pm](https://cloud.githubusercontent.com/assets/1180747/21656189/bcff5c7c-d282-11e6-9d25-dc04dc512bf9.png)

**Comment by gondzo** [comment]
@kbowerma this is wired to the actual backend API in [current challenge](https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30056064)

**Comment by kbowerma** [comment]
Good I was hopping it would.     We will need to cherry pick my pull request to update the images for #20 and #22
