### ISSUE TITLE
replace myDrone images

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/dsp-frontend#22]
From myDrones list view

 - [x] drone-lg.png  (452x293)
 - [x] drone-spec.png (454x400
 - [x] my-drone-1.png (148 x 95)
 - [x] my-drone-2.png
 - [x] my-drone-3.png
 - [x] my-drone-4.png

![screen shot 2017-01-04 at 1 36 44 pm](https://cloud.githubusercontent.com/assets/1180747/21656239/eecf4582-d282-11e6-93c2-5da3ca704764.png)

from mydrones detail
![screen shot 2017-01-04 at 1 36 59 pm](https://cloud.githubusercontent.com/assets/1180747/21656264/0453da3a-d283-11e6-8451-fc8a363b4932.png)

**Comment by gondzo** [comment]
@kbowerma any ideas for the replacement images ?

**Comment by kbowerma** [comment]
I got them.   I am almost done

**Comment by kbowerma** [comment]
sorry I meant to assign it to myself

**Comment by kbowerma** [comment]
Here is what I came up with,   see PR #23 

<img width="562" alt="screen shot 2017-01-04 at 2 48 07 pm" src="https://cloud.githubusercontent.com/assets/1180747/21658611/ea6dfe34-d28c-11e6-9af9-f8c40de83eab.png">

<img width="1048" alt="screen shot 2017-01-04 at 2 47 47 pm" src="https://cloud.githubusercontent.com/assets/1180747/21658617/f0712432-d28c-11e6-82ef-900daa22dfc0.png">
