### ISSUE TITLE
[$50] /home background images

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/dsp-frontend#34]
Fix the two background in the home component

The banner background image is found at src/routes/Home/components/HomeBanner/HomeBanner.scss and it is using a relative path to get the banner-bg-.png incorrectly.   Also How it works had the same problem.

This problem only occurs when you run ``` npm run dev ``` locally.   If you run ``` npm run start ``` the banner will work but the other drone images wont.

however when I deploy to Heroku they both seem to work fine.
 

Please fix this reference link in the corresponding scss and do a PR or let me know what is wrong with my process.

![image](https://cloud.githubusercontent.com/assets/1180747/21695214/7331face-d34e-11e6-9cc0-f3cb19067830.png)

**Comment by lstkz** [comment]
You removed this line
```
    publicPath: __DEV__ ? `http://${ip.address()}:${process.env.PORT || 3000}/` : '/',

``` 
in
d08f40e92fae492f5144a5f93997d9df4f139238

This is not correct. When you deploy to Heroku you should always use NODE_ENV=production

**Comment by kbowerma** [comment]
Payment Scheduled - DRONESERIES-6
