### ISSUE TITLE
[50$] Eslint errors

### ISSUE THREAD

**Issue by gondzo** [topcoderinc/dsp-frontend#8]
Running eslint produces 900+ errors that should be fixed.

**Comment by lstkz** [comment]
please assign to me

handle: Sky_

**Comment by lstkz** [comment]
see #9

**Comment by lstkz** [comment]
btw there are many duplicated components under different routes

**Comment by lstkz** [comment]
I would suggest merging eslint fixes to other branches, before doing any new contests.
Otherwise, branch merges will be hard.

**Comment by gondzo** [comment]
With the updated eslintrc I get many 'Parse errors in imported module './XXYY.scss' import/no-named-as-default'. Adding '"settings":{"import/ignore":[".scss$"] }"' to eslintrc is correct ?
Also, there are 132 'import/no-named-as-default' errors like
'Using exported name 'StatusDetailView' as identifier for default export  import/no-named-as-default'

**Comment by lstkz** [comment]
can you remove `node_modules` and rerun `npm i`?

**Comment by gondzo** [comment]
That does it. Running lint fix to resolve line ending issues produces the above errors.
Closing the issue.

**Comment by kbowerma** [comment]
Jira Payment record: https://apps.topcoder.com/bugs/browse/DRONESERIES-9
